### ISSUE TITLE
Direct Contact?

### ISSUE THREAD

**Issue by a01020304uk** [SomeoneElseOSM/SomeoneElse-style#1]
is there any way I can email you directly  to explain things I need and why and save messages back and forth on here. it is easier to explain and show examples by attachments on email.

**Comment by SomeoneElseOSM** [comment]
Sure: "ajt1047 at gmail.com" is the email address that I use for OSM mailing lists etc.; you can use that.

**Comment by SomeoneElseOSM** [comment]
(closing since not really an issue with this repository as such)
