### ISSUE TITLE
Render sink holes

### ISSUE THREAD

**Issue by tommycrock** [SomeoneElseOSM/SomeoneElse-style#11]
It would be nice if [sinkholes](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dsinkhole) rendered. Nodes perhaps as small grey circles, areas as a series of grey triangles pointing in to the centre. Perhaps different types should have different rendering but I'm not sure what.
Thanks!

**Comment by SomeoneElseOSM** [comment]
I've made sinkholes that are mapped as ways render as cliffs, in https://github.com/SomeoneElseOSM/SomeoneElse-style/commit/b3dbf102d1170ab89129556018f782c4fd5e4f3a .

This won't deal with most of them, which are just mapped as nodes.

**Comment by tommycrock** [comment]
Thanks. I'm not sure if you've done it so they'll necessarily render the right way round? They're treated as areas in the wiki so won't have necessarily been drawn in one direction. At least there'll be a mark for now.

**Comment by SomeoneElseOSM** [comment]
They might indeed turn out the wrong way round, but there are relatively few of them in the UK and the ones that I checked on a test rendering (Derbyshire and Yorkshire) actually came out the right way around, purely by chance.

**Comment by SomeoneElseOSM** [comment]
The database is now reloaded and these are now visible.

**Comment by tommycrock** [comment]
Thanks very much. Should I open another issue for the nodes or do you not want to render them?

**Comment by SomeoneElseOSM** [comment]
No - nodes should be OK too:

Legend:
https://map.atownsend.org.uk/maps/map/map.html#zoom=20&lat=-25.010959&lon=135.174165

In the Yorkshire Dales:
https://map.atownsend.org.uk/maps/map/map.html#zoom=16&lat=54.04413&lon=-2.09894

**Comment by tommycrock** [comment]
Great, I see it. Thanks.
