### ISSUE TITLE
parcel lockers new proposal changing tags

### ISSUE THREAD

**Issue by ttomasz** [SomeoneElseOSM/SomeoneElse-style#12]
FYI there is an ongoing vote for a proposal that would change parcel locker tags: https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_locker

**Comment by SomeoneElseOSM** [comment]
Purely by accident, there would actually be no change necessary if that was approved and everyone suddenly started using the new tag, because at https://github.com/SomeoneElseOSM/SomeoneElse-style/blob/master/style.lua#L3210 the tagging I use internally is already "amenity=parcel_locker" :)
