### ISSUE TITLE
Taginfo say that this project display route=historic

### ISSUE THREAD

**Issue by pyrog** [SomeoneElseOSM/SomeoneElse-style#17]
[route=historic](https://wiki.openstreetmap.org/wiki/Tag:route%3Dhistoric) seem not supported by your project.

Just remove the following line?

https://github.com/SomeoneElseOSM/SomeoneElse-style/blob/c5e22985caa375857f93cb6c27882e719162a239/taginfo.json#L2039

Also Taginfo say that `route=mtb` and `route=ferry` tags are valid for all OSM object types.

https://github.com/SomeoneElseOSM/SomeoneElse-style/blob/c5e22985caa375857f93cb6c27882e719162a239/taginfo.json#L2040-L2041

Just add `"object_types":["relation"]` ?

```json
{ "key": "route", "value": "mtb", "object_types":["relation"], "description": "Detect MTB networks" }, 
{ "key": "route", "value": "ferry", "object_types":["relation"], "description": "Show ferry routes" }, 
```

**Comment by SomeoneElseOSM** [comment]
The issue here is exactly the same as https://github.com/SomeoneElseOSM/mkgmap_style_ajt/issues/1#issuecomment-1511652254 .

That's the way that taginfo chooses to show data, and to be honest I think that it is a good decision on their part to do it that way.
