### ISSUE TITLE
Render name on place=islet

### ISSUE THREAD

**Issue by osmuser63783** [SomeoneElseOSM/SomeoneElse-style#20]
I've noticed your map doesn't show names on place=islet.

Not sure if this belongs in this repo or the other, sorry!

**Comment by SomeoneElseOSM** [comment]
So it doesn't!

One of the bigger ones is https://www.openstreetmap.org/way/200745352 , which is the big thing to the east at https://map.atownsend.org.uk/maps/map/map.html#14/56.1570/-5.5423 (the two smaller named things are "place=island").  Rendering that like "island" at z13 would certainly make sense.

However, at the other end of the scale is https://www.openstreetmap.org/way/238155320#map=13/49.9570/-6.2568 , and rendering that at z13 would obviously be silly.  A label there would probably make sense from z22 https://map.atownsend.org.uk/maps/map/map.html#22/49.95960/-6.26277 .  

Also probably z22 for named nodes https://overpass-turbo.eu/s/1DW1 .

> Not sure if this belongs in this repo or the other, sorry!

It's going to need changes to both, I think.

**Comment by SomeoneElseOSM** [comment]
This is now done.  Islands and islets are treated identically, with the zoom level at which either appears depending on polygon size.  Nodes for both are displayed from zoom 20.

You can see the effect zooming in and out at http://map.atownsend.org.uk/maps/map/map.html#12/53.6984/-0.5881 , and on larger islands here: https://map.atownsend.org.uk/maps/map/map.html#8/57.594/-6.603 .  

For nodes, see here http://map.atownsend.org.uk/maps/map/map.html#19/52.75767/-0.90776 (zoom in).

Larger islands should show at lower zoom levels still (Ireland at 7, GB at 6) https://map.atownsend.org.uk/maps/map/map.html#7/53.550/-6.520 but they'll tend to be overlaid by other data, even at those low zooms.
