### ISSUE TITLE
Farmland rendering

### ISSUE THREAD

**Issue by trigpoint** [SomeoneElseOSM/SomeoneElse-style#6]
There are various issues in OSM relating to the mistagging of pasture as meadow, this looses the meaning of meadow as well as encouraging tagging for the renderer.

Some of us are begining to use the subtags of farmland=arable and farmland=pasture to distingush the most common types found in lowland Great Britain.

It would be very useful to be able to see these rendered on an outdoor style.

Possibly render farmland=arable as farmland is currently rendered and render farmland=pasture as the standard style currently renders farmland using eef0d5.

The attached image is an example of how the style could look as a mix of arable, pasture and meadow.

![image](https://user-images.githubusercontent.com/8437076/70870550-98f07780-1f8c-11ea-8be2-121003d9f3a0.png)

**Comment by SomeoneElseOSM** [comment]
Should be addressed by the release https://github.com/SomeoneElseOSM/SomeoneElse-style/blob/master/changelog.md#21122019-release .  The new colour I've used (for "grassy farmland" and "agricultural meadow") is at https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/blob/master/landcover.mss#L38 - half way between existing meadow and farmland.

**Comment by SomeoneElseOSM** [comment]
Yes - now fixed.
